### ISSUE TITLE
The word injection should be in quotes.

### ISSUE THREAD

**Issue by JakeWharton** [denley/PreferenceInjector#13]
ButterKnife purports to be an injection library solely as a joke (poking fun at RoboGuice). As such, its usages of the word injection are always in quotes. It has nothing to do with dependency injection. In fact, the next major version will move from `@InjectView` to `@BindView` or `@FindVIew` and I will be removing all usages of the word injection.

While I don't expect you to change this library in that same fashion, putting injection in quotes at least covers your ass for the fact that this or any of these libraries (including Butter Knife) are not true injection.

**Comment by JakeWharton** [comment]
Also, feel free to ignore :grinning: , I just enjoy the joke aspect of the quotes. Nice library, by the way.

**Comment by denley** [comment]
@JakeWharton Thanks for the feedback. I will take your advice on board and add the quotes. I don't want to break any standards.

This library is made in the image of Butter Knife (I literally started with a copy of Butter Knife and changed it into this, which is why I attributed you in the license section). I would like to maintain the familiarity for the users' sake, so I will probably update the annotation names too once you have do so for Butter Knife.

Thanks again.

**Comment by JakeWharton** [comment]
FYI, Butter Knife switched to `@Bind` and `bind()` to finally put the nail in the "injection" coffin, at least for views.

**Comment by denley** [comment]
Thanks for letting me know. I've been using Butter Knife 7.0.0 today actually.

I intend to do the same for this library too sometime soon. I guess I should use `@BindPreference` or something to avoid import conflicts with Butter Knife.

**Comment by JakeWharton** [comment]
Yeah I guess I inadvertently monopolized `@Bind`. I didn't think about other libs. Maybe I'll switch to `@BindView` in v8.
