### ISSUE TITLE
Issue when Butterknife and PrefenceInjector are used in same project

### ISSUE THREAD

**Issue by adaneam** [denley/PreferenceInjector#23]
I get following error when using both Butterknife and PrefenceInjector

Error:Execution failed for task ':app:packageDebug'.

> Duplicate files copied in APK META-INF/services/javax.annotation.processing.Processor
>     File 1: D:\Users\admin.gradle\caches\modules-2\files-2.1\com.jakewharton\butterknife\6.1.0\63735f48b82bcd24cdd33821342428252eb1ca5a\butterknife-6.1.0.jar
>     File 2: E:\TestApp\app\build\intermediates\exploded-aar\me.denley.preferenceinjector\PreferenceInjector\2.2.1\jars\classes.jar

**Comment by denley** [comment]
Hi. Thanks for using `PreferenceInjector`

Your issue occurs because you are using more than one annotation processor in your project (it will occur with any two, e.g. ButterKnife + Dagger), which causes a conflict when packaging your project into an apk file.

The annotation processors have already done their job by the time you package the app into an apk file, so you can fix this by simply excluding the conflicting file.

You can do this by adding the following to your build.gradle file:

``` groovy
android {
    // you will have some existing configuration here, such as the app ID and SDK version
    // ...

    packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
    }
}
```
