### ISSUE TITLE
value as int (string resource)

### ISSUE THREAD

**Issue by mlostekk** [denley/PreferenceInjector#26]
Is it possible to use it with a string resource as value for 'value' ? I mean like this

`@InjectPreference(value = R.string.SP_OFFSET_AUDIO, listen = true)`

**Comment by denley** [comment]
Currently this is not supported, but I'm open to the idea of supporting this for future versions.

Due to java language constraints, there's no way for an annotation to be able to accept both a String or an int as its value, so it would mean using a different annotation name for the one that accepts the int (e.g. `@InjectPreferenceStringRes(R.string.pref_foo_bar)`).

**Comment by mlostekk** [comment]
Okay, could you give me a hint where to start  in order to change it from string to int.(and especially where to resolve the R.string.xxx integer to the real string?) I am quite new to annotations :)

I want to use your lib, but have to change it from string to int because i am just working with string resources for my prefs

**Comment by mlostekk** [comment]
Well, i tried a bit, but i guess its nothing for annotations beginners :) thanks for thinking about this as a feature! would love to see it.

**Comment by denley** [comment]
You can't use a value from a String resource currently. You have to use the raw preference String, or a static final String variable. This is because the annotation processing occurs at compile time, so it must be resolvable at that point.

**Comment by mlostekk** [comment]
Was this implemented in the new version 3?

still would love to use your lib, but in order to be in-line with official documentation and examples (http://developer.android.com/training/basics/data-storage/shared-preferences.html) i would need to access the keys via a string resource.

**Comment by mlostekk** [comment]
And by the way, how is it possible to bind a static final String element?

@BindPref(value = Pref.KEY_ NAME ....

does not work.

**Comment by denley** [comment]
I'm sorry to say that it's still not supported in version 3.

I'm not sold on the feature at this point. I'd rather the library be opinionated and promote a particular implementation style in order to minimise its API.

I think it's best to use static final Strings for preference keys when using this library, as they are resolvable at compile-time (and hence more performant). Since preference keys don't need to depend on configuration changes (they aren't translated between languages) there's no need for them to be defined as String resources.

I see the reasoning of reducing duplicated String definitions when using preference xml files, but since they very rarely change in the life of an application I think this benefit is trivial.

**Comment by denley** [comment]
What exactly is not working about binding a `static final String` preference key? Are you getting a compiler error? or is it not behaving as expected at runtime? The sample module demonstrates a working/tested implementation of the `@BindPref` annotation.

**Comment by mlostekk** [comment]
Oh, sorry, `static final String` is working... I was trying to do it with `static String` in order to initialize the variables in the code to the values from the xml in order to eliminate the redundancy...

Do you have any suggestions to remove the redundancy `code vs. xml values`?

**Comment by denley** [comment]
It must be `static final` because the annotation processor runs at compile-time (only static final variables are resolved at this point). Runtime changes can't be made on the annotations as they have already been processed.

I think the best thing to do is to make a class that defines all of your preference keys and default values as `public static final` variables (in version 3 default values are global to your application), and refer to the constants in this class throughout your application. If you need the keys in a preferences xml file, then just copy the preference key as String literal. This does duplicate the key but in all likelihood it will never change at all so it won't cause a problem (it's not a user-facing String).

I think I should update the sample app to use this situation I described above, as it's probably a common example. It currently just uses String literals, and doesn't have a preferences xml file.

**Comment by denley** [comment]
There's a new library out from the Flipboard team called Psync (https://github.com/Flipboard/psync), which will generate java classes from preferences xml files. This will solve the key duplication issue we have discussed.

Psync is completely compatible with PreferenceBinder as it puts `public static final String` keys in the generated classes (which you can then use in `@BindPref` annotations.

**Comment by mlostekk** [comment]
brilliant! Thanks!
