### ISSUE TITLE
bindTo type "INPUT"

### ISSUE THREAD

**Issue by mlostekk** [denley/PreferenceInjector#33]
What about a `bindType=INPUT` that behaves like `TEXT` but saves the user changes back to the preference?

**Comment by denley** [comment]
Good idea :thumbsup:

Since the text listener can apply to TextView ([TextView#addTextChangedListener](http://developer.android.com/reference/android/widget/TextView.html#addTextChangedListener%28android.text.TextWatcher%29)) I will probably just add this behaviour to the existing `TEXT` type. I can't imagine a situation where you would want to automatically load preference value changes but not also save them when the user changes it (the `CHECKED` type does this by default for the same reason).

**Comment by mlostekk** [comment]
Eveb better :)

Denley Bihari notifications@github.com schrieb am Di., 18.08.2015, 6:19:
