### ISSUE TITLE
compared to rxpreferences....?

### ISSUE THREAD

**Issue by sirvon** [denley/PreferenceInjector#34]
not only thanks for the code but thanks for the docs!

how would you compare your implementation on preference binding to the rx camp's version?

**Comment by denley** [comment]
No problem. I'm glad you find this library useful :)

I've only glossed over the rxpreferences library (I haven't actually used it yet), so the following is based on my limited understanding of it.

I think that the biggest benefit of using this library (PreferenceBinder) is that it results in smaller and more readable code. Rxjava can get messy in Android because you can't use lambdas, so you have anonymous classes everywhere. With PreferenceBinder you just need to add an annotation to a field or method to bind the preference values, which makes it very readable. This extends to widget binding too, you can bind a preference key to a checkbox (for example) with a single annotation, using the rx libraries this would not be a simple one-liner.

Using rxpreferences has the benefit of being able to leverage the observable operators in order to combine observables. If you ever find you need to filter/combine/transform preference values then rxjava will probably make this a lot easier.

When concurrency/performance is an issue I'd suggest to use rxpreferences over this library, as it will ensure all of the loading of preference values occurs off the main thread. In PreferenceBinder, it's all done on the main thread (which is fine for just loading a few short preference values, but could cause a problem with loading very long Strings, or binding a very large number of key/value pairs. Loading values could actually be a benefit, as it ensures that all values are loaded immediately after calling `PreferenceBinder.bind` and can be used inside the lifecycle methods (`onCreate`, 'onStart`, etc.). If this is of benefit to your app then PreferenceBinder might be the better choice.
