### ISSUE TITLE
Overload `inject` to accept just a Fragment

### ISSUE THREAD

**Issue by robisaks** [denley/PreferenceInjector#8]
If the preference injector is added to a fragment, it does not appear to populate the fields correctly.

**Comment by denley** [comment]
I've just tested using a `Fragment`, and it appears to work fine for me. Can you elaborate on the problem? If you could provide a sample of code that is not working as expected it would help.

I added the test I just made to the sample module, so you can now see a sample case using a `Fragment` there: https://github.com/denley/PreferenceInjector/blob/master/sample/src/main/java/me/denley/preferenceinjector/SampleFragment.java

The only real difference is that you have to use `PreferenceInjector.inject(getActivity(), this)` for `Fragment`s instead of just `PreferenceInjector.inject(this)`;

**Comment by robisaks** [comment]
@denley thanks! Looks like I was not initializing it correctly.

**Comment by denley** [comment]
@robisaks Thanks for the report.

There's actually no reason it has to be this way. The constructor is overloaded for `Activity`, `View` and `Dialog`. There's no reason the same can't be done for `Fragment` as `getActivity` is public. It would certainly make the API simpler. I will take that on board as an issue.

**Comment by denley** [comment]
Version 2.1.1 has been released with this change. You can now call `PreferenceInjector.inject(this)` from a `Fragment`
